### ISSUE TITLE
does not run on vnc  BitcoinGUI::createTrayIcon() - segmentation fault

### ISSUE THREAD

**Issue by entaro2k** [freakcoderz/FreakChain#1]
gdb ./FreakChain
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./FreakChain...(no debugging symbols found)...done.
(gdb) run
Starting program: /srv/freakchain/FreakChain
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
No systemtrayicon available

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff596ed71 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
(gdb) backtrace
#0  0x00007ffff596ed71 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#1  0x00007ffff59b475c in QWidget::insertAction(QAction*, QAction*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#2  0x000000000045d765 in BitcoinGUI::createTrayIcon() ()
#3  0x0000000000462e60 in BitcoinGUI::BitcoinGUI(QWidget*) ()
#4  0x000000000043152c in main ()
(gdb)

**Comment by freakcoderz** [comment]
Resolved with latest commit.
